import type { Metadata } from "next";
import { Iceland } from "next/font/google";
import "./globals.css";

import Navbar from "./comp/navbar";
import Footer from "./comp/footer";

const iceland = Iceland({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={iceland.className}>
        <Navbar/>
        <main className="flex-grow">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
